# Header
menu:
  Home: /
  Donate: /donate
  About: /about
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
