# Header
menu:
  Home: /
  Donate: /donate
  About: /about
  Calendar: /calendar

# Content
excerpt_link: Read More
fancybox: false

# Miscellaneous
google_analytics: UA-79743620-1
favicon: /first/images/Logo.png
twitter:
google_plus:
fb_admins:
fb_app_id:
pictures_per_row: 4
max_pictures: 8
